describe('Test group info component', () => {
    it('Open moderation page', () => {
      cy.visit('http://localhost:4200/login')
        cy.contains('Login').click()
        cy.get('#mat-input-0').type('renzo@ufl.edu')
        cy.get('#mat-input-1').type('123')
        cy.contains('Sign In').click()
        cy.saveLocalStorage()
      cy.visit('http://localhost:4200/moderation')
    })
    it('Deny Request', () => {
      cy.restoreLocalStorage()
      cy.contains('Deny').click()
      cy.wait(100)
      cy.contains('Deny').click()
      cy.wait(100)
      cy.contains('Deny').click()
      cy.wait(100)
      cy.contains('Deny').click()
      cy.wait(100)
    })
    it('Approve Request', () => {
      cy.restoreLocalStorage()
      cy.contains('Approve').click()
      cy.wait(100)
      cy.contains('Approve').click()
      cy.wait(100)
      cy.contains('Approve').click()
      cy.wait(100)
      cy.contains('Approve').click()
      cy.wait(100)
    })
    it('Acknowledge Issue', () => {
      cy.restoreLocalStorage()
      cy.contains('Acknowledge').click()
      cy.wait(100)
      cy.contains('Acknowledge').click()
      cy.wait(100)
      cy.contains('Acknowledge').click()
      cy.wait(100)
      cy.contains('Acknowledge').click()
      cy.wait(100)
    })
  })
